[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "changepointmodel"
version = "1.2.2"
description = "Energy changepoint modeling and related methodologies"
authors = [ "cunybpl <dev@cunybpl.org>",]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
pydantic = "^1.8.2"
nptyping = "^1.4.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"

[tool.poetry.dependencies.curvefit-estimator]
git = "https://github.com/cunybpl/curvefit-estimator.git"
tag = "v0.2.0"
