name: unittests

on:
  pull_request:
    branches:
      - development
      - stable-release 
      
  push:
    branches:
      - development
      

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install poetry build system and dependencies
        run: |
          export POETRY_VIRTUALENVS_CREATE=false
          curl -sSL https://install.python-poetry.org | python3 - --version 1.3.2
          pip install -U pip
          poetry install
      
      - name: Run tests
        run: |  
          make test